### PR TITLE
Travis CI build on commit & pull requests plus icon in readme

### PR DESCRIPTION
**Pull request by artyomtrityak**
That's a good idea to have Travis CI build on commit and also have same for pull requests.
Next thing to do is setup Travis CI and github Setting "Integrations & services" section.

Example here: https://github.com/artyomtrityak/Atlantis

How it looks like:

screenshot 2016-11-15 16 09 35

### CODE REVIEW

**Comment by artyomtrityak** [comment]
anyone here?

**Comment by sgb** [comment]
But responding might mean I have to work out how to use Travis...

**Comment by artyomtrityak** [comment]
@sgb cool, just wanted to know that this PR has not been missed

**Comment by Loriaki** [comment]
On Tue, Nov 22, 2016 at 05:23:01PM -0800, Artyom Trityak wrote:
> anyone here?

Sure ... 

Need to dig into this Builder Service ... but
if we would get it to work, it would be a nice feature .
One more Thing on the TODO List

**Comment by Loriaki** [comment]
I did the merge by Hand, so it reflects the repository and Travis links correct.

**Comment by Loriaki** [comment]
At least Travis-CI works now :-)

**Comment by artyomtrityak** [comment]
Hooray! :)

**Pull request closed without merging**
