### PR TITLE
Updated Makefile to avoid recursive make

### PR DESCRIPTION
**Pull request by nedbrek**
Automatically generate dependencies

### CODE REVIEW

**Review by artyomtrityak — APPROVED** [review]

**Comment by artyomtrityak** [comment]
Builds are failing ^

**Review by artyomtrityak — CHANGES_REQUESTED** [review]
Build is failing

**Comment by nedbrek** [comment]
Sorry, I didn't see this failed. Easy fix.

**Review by valdisz — APPROVED** [review]

**Comment by valdisz** [comment]
@nedbrek @jt-traub there were some good changes, but was not merged and now we have conflicts :(
can you help with this?

**Comment by jt-traub** [comment]
> @nedbrek @jt-traub there were some good changes, but was not merged and now we have conflicts :( can you help with this?

I can.. but i am not convinced it's necessarily beneficial (or detrimental).. I have seen arguments both for and against recursive make and have never been persuaded that either way is *fundamentally* better.

**Comment by jt-traub** [comment]
I have take the bits to automate counting of cities, and the small fix to display practice and added them to a branch of collected PR fixes which I will merge once all tests pass, etc.  Closing this PR since I am going to ignore the makefile changes for now.

**Comment by jt-traub** [comment]
Changes, except for the makefile reorg are in PR #186

**Pull request closed without merging**
