### PR TITLE
Checks orders checks password, too.

### PR DESCRIPTION
**Pull request by sheckman16**
This reads game.in and players.in to get the passwords from players.in.

A test in a local game ran as shown below.  The local game contained game.in, players.in, and orders.3.  Players.in had a password for faction 3 of "mypassword".  Orders.3 specified a password of "notmypassword".  The orders checker detects the error.  When the password in orders.3 is changed to "mypassword", the orders checker reports no errors.

L$ ls
game.in  orders.3  players.in
L$ grep -A2 'Faction (3)' players.in 
Name: Faction (3)
Email: NoAddress
Password: mypassword
L$ cat orders.3
#atlantis 3 "notmypassword"
#end
L$ ../../Atlantis/neworigins/neworigins check orders.3 check.out && cat check.out
Atlantis Engine Version: 5.2.5 (beta)
NewOrigins, Version: 3.0.0 (beta)

Saved Game Engine Version: 5.2.5 (beta)
Saved Rule-Set Version: 3.0.0 (beta)
Reading the regions...
Setting up the neighbors...

*** Error: Incorrect password on #atlantis line. ***
#atlantis 3 "notmypassword"
#end

1 error found!
L$ sed -i s/notmypassword/mypassword/ orders.3
You have new mail in /var/mail/stan
L$ ../../Atlantis/neworigins/neworigins check orders.3 check.out && cat check.out
Atlantis Engine Version: 5.2.5 (beta)
NewOrigins, Version: 3.0.0 (beta)

Saved Game Engine Version: 5.2.5 (beta)
Saved Rule-Set Version: 3.0.0 (beta)
Reading the regions...
Setting up the neighbors...
#atlantis 3 "mypassword"
#end

No errors found.
L$

### CODE REVIEW

**Review by artyomtrityak — COMMENTED** [review]
This PR has plenty of changes seem not related to password check.

**Comment by sheckman16** [comment]
That was unintended; I'll try again being sure I have a clean branch.

**Review by artyomtrityak — CHANGES_REQUESTED** [review]
Please cleanup all non-related changes

**Comment by jt-traub** [comment]
Adding this change to my branch to clean up some outstanding PRs .  Sadly it could not be merged directly due to other conflicting changes which had occurred in the interim.  Closing this PR as it is captured in that branch now.

**Comment by jt-traub** [comment]
Changes are in #186

**Pull request closed without merging**
